// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNa06fYyioZKaGtIGq_u4WpfSOja0ubt0',
    appId: '1:524330739259:web:558754e043c5bc090fde1e',
    messagingSenderId: '524330739259',
    projectId: 'yamani-app-alking',
    authDomain: 'yamani-app-alking.firebaseapp.com',
    storageBucket: 'yamani-app-alking.firebasestorage.app',
    measurementId: 'G-7MP5W8N7ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCi14MLoDq2j9fxglIJWVFufb4lpWx1U',
    appId: '1:524330739259:android:509c228a157154de0fde1e',
    messagingSenderId: '524330739259',
    projectId: 'yamani-app-alking',
    storageBucket: 'yamani-app-alking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrcWAkuiMuFYD0a_dm6YvJLFvCoC5apS0',
    appId: '1:524330739259:ios:90feae4407690b1c0fde1e',
    messagingSenderId: '524330739259',
    projectId: 'yamani-app-alking',
    storageBucket: 'yamani-app-alking.firebasestorage.app',
    iosBundleId: 'com.example.tempApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrcWAkuiMuFYD0a_dm6YvJLFvCoC5apS0',
    appId: '1:524330739259:ios:90feae4407690b1c0fde1e',
    messagingSenderId: '524330739259',
    projectId: 'yamani-app-alking',
    storageBucket: 'yamani-app-alking.firebasestorage.app',
    iosBundleId: 'com.example.tempApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNa06fYyioZKaGtIGq_u4WpfSOja0ubt0',
    appId: '1:524330739259:web:2665d0329785f1bd0fde1e',
    messagingSenderId: '524330739259',
    projectId: 'yamani-app-alking',
    authDomain: 'yamani-app-alking.firebaseapp.com',
    storageBucket: 'yamani-app-alking.firebasestorage.app',
    measurementId: 'G-NFSBYB3LQK',
  );
}
