// lib/screens/auth_gate.dart

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'search_screen.dart';
import '../services/permissions_service.dart';
import '../services/contacts_service.dart';

class AuthGate extends StatefulWidget {
  const AuthGate({super.key});

    @override
      State<AuthGate> createState() => _AuthGateState();
      }

      class _AuthGateState extends State<AuthGate> {
        bool _hasSynced = false;
          bool _isLoading = true;

            @override
              void initState() {
                  super.initState();
                      _checkSyncStatus();
                        }

                          Future<void> _checkSyncStatus() async {
                              final prefs = await SharedPreferences.getInstance();
                                  setState(() {
                                        _hasSynced = prefs.getBool('has_synced_contacts') ?? false;
                                              _isLoading = false;
                                                  });
                                                    }

                                                      Future<void> _handleSync() async {
                                                          final permissionsService = PermissionsService();
                                                              final contactsService = ContactsService();

                                                                  bool permissionGranted = await permissionsService.requestContactsPermission();
                                                                      if (permissionGranted) {
                                                                            // إظهار مؤشر تحميل أثناء المزامنة
                                                                                  showDialog(
                                                                                          context: context,
                                                                                                  barrierDismissible: false,
                                                                                                          builder: (context) => const Center(child: CircularProgressIndicator()),
                                                                                                                );

                                                                                                                      await contactsService.syncContacts();
                                                                                                                            
                                                                                                                                  final prefs = await SharedPreferences.getInstance();
                                                                                                                                        await prefs.setBool('has_synced_contacts', true);

                                                                                                                                              Navigator.of(context).pop(); // إغلاق مؤشر التحميل

                                                                                                                                                    setState(() {
                                                                                                                                                            _hasSynced = true;
                                                                                                                                                                  });
                                                                                                                                                                      }
                                                                                                                                                                        }

                                                                                                                                                                          @override
                                                                                                                                                                            Widget build(BuildContext context) {
                                                                                                                                                                                if (_isLoading) {
                                                                                                                                                                                      return const Scaffold(
                                                                                                                                                                                              body: Center(child: CircularProgressIndicator()),
                                                                                                                                                                                                    );
                                                                                                                                                                                                        }

                                                                                                                                                                                                            if (_hasSynced) {
                                                                                                                                                                                                                  return const SearchScreen();
                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                            return Scaffold(
                                                                                                                                                                                                                                    backgroundColor: const Color(0xFF007BFF),
                                                                                                                                                                                                                                            body: Center(
                                                                                                                                                                                                                                                      child: Padding(
                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(24.0),
                                                                                                                                                                                                                                                                              child: Column(
                                                                                                                                                                                                                                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                          const Icon(Icons.sync, color: Colors.white, size: 80),
                                                                                                                                                                                                                                                                                                                                          const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                          const Text(
                                                                                                                                                                                                                                                                                                                                                                            'مزامنة لمرة واحدة',
                                                                                                                                                                                                                                                                                                                                                                                              style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                  color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'يعتمد يماني كاشف على المساهمة المجتمعية. يرجى المزامنة للمساعدة في بناء قاعدة البيانات.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style: TextStyle(color: Colors.white70, fontSize: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: _handleSync,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                foregroundColor: const Color(0xFF007BFF),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: const EdgeInsets.symmetric(horizontal: 50, vertical: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textStyle: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: const Text('موافق والمزامنة الآن'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    