// lib/screens/search_screen.dart

import 'package:flutter/material.dart';
import '../services/firestore_service.dart';
import '../models/search_result.dart';
import '../widgets/result_card.dart';

class SearchScreen extends StatefulWidget {
  const SearchScreen({super.key});

    @override
      State<SearchScreen> createState() => _SearchScreenState();
      }

      class _SearchScreenState extends State<SearchScreen> {
        final TextEditingController _searchController = TextEditingController();
          final FirestoreService _firestoreService = FirestoreService();

            bool _isLoading = false;
              SearchResult? _searchResult;
                String? _message;

                  void _performSearch() async {
                      if (_searchController.text.isEmpty) return;

                          setState(() {
                                _isLoading = true;
                                      _searchResult = null;
                                            _message = null;
                                                });

                                                    try {
                                                          final result = await _firestoreService.searchNumber(_searchController.text);
                                                                if (result != null) {
                                                                        setState(() {
                                                                                  _searchResult = result;
                                                                                          });
                                                                                                } else {
                                                                                                        setState(() {
                                                                                                                  _message = 'هذا الرقم غير موجود في قاعدة البيانات حالياً.';
                                                                                                                          });
                                                                                                                                }
                                                                                                                                    } catch (e) {
                                                                                                                                          setState(() {
                                                                                                                                                  _message = 'حدث خطأ أثناء البحث. يرجى التحقق من اتصالك بالإنترنت.';
                                                                                                                                                        });
                                                                                                                                                            }

                                                                                                                                                                setState(() {
                                                                                                                                                                      _isLoading = false;
                                                                                                                                                                          });
                                                                                                                                                                            }

                                                                                                                                                                              @override
                                                                                                                                                                                Widget build(BuildContext context) {
                                                                                                                                                                                    return Scaffold(
                                                                                                                                                                                          appBar: AppBar(
                                                                                                                                                                                                  title: const Text('يماني كاشف'),
                                                                                                                                                                                                        ),
                                                                                                                                                                                                              body: SingleChildScrollView(
                                                                                                                                                                                                                      child: Padding(
                                                                                                                                                                                                                                padding: const EdgeInsets.all(20.0),
                                                                                                                                                                                                                                          child: Column(
                                                                                                                                                                                                                                                      crossAxisAlignment: CrossAxisAlignment.center,
                                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                              const Text(
                                                                                                                                                                                                                                                                                                              'يماني كاشف',
                                                                                                                                                                                                                                                                                                                              style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                fontSize: 36,
                                                                                                                                                                                                                                                                                                                                                                  fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                    color: Color(0xFF1D2D44),
                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                              Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              'دليلك الأول لكشف الأرقام في اليمن',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: Colors.grey[600],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            controller: _searchController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: TextAlign.right,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            keyboardType: TextInputType.phone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style: const TextStyle(fontSize: 18),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              hintText: 'أدخل الرقم هنا...',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                prefixIcon: IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    icon: const Icon(Icons.search, color: Color(0xFF007BFF)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: _performSearch,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: BorderRadius.circular(30.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderSide: BorderSide.none,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        filled: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fillColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            contentPadding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 20.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // منطقة عرض النتائج أو التحميل أو الرسائل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (_isLoading)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: EdgeInsets.only(top: 50.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: CircularProgressIndicator(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (_message != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.only(top: 30.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _message!,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: const TextStyle(color: Colors.red, fontSize: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (_searchResult != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ResultCard(result: _searchResult!),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  